backend:
  name: github
  repo: qhd-zhaoxin/xin-zhao
  branch: main
  site_domain: xin-zhao.netlify.app

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "research"
    label: "Research"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "teaching"
    label: "Teaching"
    folder: "content/teaching"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "publications"
    label: "Publications"
    folder: "content/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "travels"
    label: "Travels"
    folder: "content/travels"
    create: true
    slug: "{{slug}}"
    extension: md
    format: yaml-frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "ski"
    label: "Ski"
    folder: "content/ski"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "badminton"
    label: "Badminton"
    folder: "content/badminton"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Xin Zhao" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
